# Docker Compose

version: '3'

services:
  mysql:
    container_name: toy2-mysql
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_USERNAME: ${LOCAL_MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${LOCAL_MYSQL_PASSWORD}
      MYSQL_DATABASE: fc_sns
      TZ: Asia/Seoul
    volumes:
      - ${LOCAL_MYSQL_VOLUME_PATH}:/var/lib/mysql
    ports:
      - ${LOCAL_MYSQL_PORT}:3306
