# Docker Compose

version: '3'

services:
  mysql:
    container_name: toy3-mysql
    image: mysql:8.0
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${LOCAL_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${LOCAL_MYSQL_PASSWORD}
      MYSQL_DATABASE: fc_sns
      TZ: Asia/Seoul
    volumes:
      - ${LOCAL_MYSQL_VOLUME_PATH}:/var/lib/mysql
    ports:
      - ${LOCAL_MYSQL_PORT}:3306
  redis:
    container_name: toy3-redis
    image: redis:7.2
    command: redis-server --port 6379
    volumes:
      - ${LOCAL_REDIS_VOLUME_PATH}:/data
    ports:
      - ${LOCAL_REDIS_PORT}:6379
